/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 14
#define YY_END_OF_BUFFER 15
static yyconst short int yy_accept[130] =
    {   0,
        0,    0,   15,   12,   11,   11,   12,    2,    4,   12,
        2,    2,    2,   12,    2,    7,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    3,   11,    0,
        3,    0,    7,    8,    0,    7,    5,   13,    0,    6,
        0,    5,    5,    0,    0,    0,    1,    0,    0,    0,
        0,    9,   10,    7,    8,    7,    0,    1,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    7,    7,    0,
        0,    0,    1,    0,    0,    0,    0,    7,    7,    0,
        0,    0,    0,    0,    1,    0,    7,    7,    0,    1,
        0,    0,    7,    0,    0,    0,    1,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    5,    1,    6,    7,    6,
        6,    8,    9,    6,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,    6,    1,   14,
       15,   16,    1,    1,   17,   17,   17,   17,   17,   18,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
        6,    1,    6,   19,   20,    1,   21,   17,   22,   23,

       24,   25,   17,   26,   27,   17,   17,   28,   17,   29,
       30,   17,   17,   31,   32,   33,   34,   35,   36,   17,
       17,   17,    6,    1,    6,   37,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[38] =
    {   0,
        1,    1,    1,    2,    1,    1,    3,    1,    1,    1,
        1,    1,    4,    1,    1,    1,    4,    4,    1,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    1
    } ;

static yyconst short int yy_base[174] =
    {   0,
        0,    0,  365,  366,   36,   38,    0,  327,  366,    0,
      326,   29,   30,  349,  366,   33,  345,  345,   32,   34,
       44,   36,   40,   45,   58,   42,   60,  366,   48,  355,
      366,  351,  344,  343,  342,   48,  366,  334,  333,  366,
       54,  337,  336,   56,   57,   55,  330,   63,   70,   71,
      345,  366,  366,  335,  334,   81,  326,  325,   75,   80,
       82,   83,   84,   85,   88,   89,  340,  330,  102,  322,
       94,   96,  321,   90,  100,  102,  336,  326,  114,  318,
      108,  104,  110,  112,  317,  332,  322,  122,  314,  313,
      114,  328,  366,  131,  300,  326,  366,  325,  324,  323,

      322,  321,  320,  319,  318,  317,  316,  315,  314,  313,
      312,  311,  310,  309,  308,  307,  306,  305,  304,  303,
      302,  301,  300,  299,  298,  297,  147,  142,  366,  144,
      148,  139,  152,  135,  156,  132,  160,   89,  164,   77,
      168,  172,  176,  180,  184,  188,  192,  196,  200,  204,
      208,  212,  216,  220,  224,  228,  232,  236,  240,  244,
      248,  252,  256,  260,  264,  268,  272,  276,  280,  284,
      288,  292,  296
    } ;

static yyconst short int yy_def[174] =
    {   0,
      129,    1,  129,  129,  129,  129,  130,  129,  129,  131,
      129,  129,  129,  129,  129,  129,  129,  129,  132,  132,
      129,  132,  132,  132,  132,  132,  132,  129,  129,  133,
      129,  129,  129,  129,  129,  129,  129,  134,  134,  129,
      134,  129,  129,  134,  134,  134,  134,  134,  134,  134,
      135,  129,  129,  129,  129,  129,  136,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  137,  129,  129,  138,
      138,  138,  138,  138,  138,  138,  139,  129,  129,  140,
      140,  140,  140,  140,  140,  141,  129,  129,  129,  129,
      129,  142,  129,  129,  129,  143,  129,  144,  145,  146,

      147,  148,  149,  150,  151,  152,  153,  154,  155,  156,
      157,  158,  159,  160,  161,  162,  163,  164,  165,  166,
      167,  168,  169,  170,  171,  172,  173,  129,    0,  129,
      129,  129,  129,  129,  129,  129,  129,  129,  129,  129,
      129,  129,  129,  129,  129,  129,  129,  129,  129,  129,
      129,  129,  129,  129,  129,  129,  129,  129,  129,  129,
      129,  129,  129,  129,  129,  129,  129,  129,  129,  129,
      129,  129,  129
    } ;

static yyconst short int yy_nxt[404] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,    4,   19,   20,   21,    4,
       19,   22,   19,   23,   19,   19,   24,   19,   19,   19,
       25,   19,   19,   19,   26,   27,   28,   29,   29,   29,
       29,   33,   33,   35,   38,   36,   38,   42,   38,   29,
       29,   40,   38,   40,   38,   40,   44,   38,   35,   40,
       56,   40,   43,   41,   40,   31,   31,   45,   46,   47,
       38,   49,   38,   40,   40,   40,   40,   40,   59,   40,
       89,   48,   40,   63,   58,   50,   60,   62,   61,   40,
       40,   35,   80,   69,   40,   64,   65,   66,   71,   40,

       72,   40,   40,   40,   40,   73,   74,   40,   40,   40,
       73,   73,   35,   40,   79,   40,   76,   82,   75,   40,
       83,   40,   81,   40,   35,   85,   88,   40,   90,   40,
       84,   40,   35,   40,   94,   70,   91,   95,   57,   90,
       90,   35,   39,   94,   30,   52,   30,   30,   32,   32,
       52,   32,   51,   51,   51,   51,   67,   67,   67,   67,
       77,   77,   77,   77,   86,   86,   86,   86,   92,   92,
       92,   92,   96,   96,   96,   96,   98,   98,   98,   98,
       99,   99,   99,   99,  100,  100,  100,  100,  101,  101,
      101,  101,  102,  102,  102,  102,  103,  103,  103,  103,

      104,  104,  104,  104,  105,  105,  105,  105,  106,  106,
      106,  106,  107,  107,  107,  107,  108,  108,  108,  108,
      109,  109,  109,  109,  110,  110,  110,  110,  111,  111,
      111,  111,  112,  112,  112,  112,  113,  113,  113,  113,
      114,  114,  114,  114,  115,  115,  115,  115,  116,  116,
      116,  116,  117,  117,  117,  117,  118,  118,  118,  118,
      119,  119,  119,  119,  120,  120,  120,  120,  121,  121,
      121,  121,  122,  122,  122,  122,  123,  123,  123,  123,
      124,  124,  124,  124,  125,  125,  125,  125,  126,  126,
      126,  126,  127,  127,  127,  127,  128,  128,  128,  128,

       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       97,   52,   40,   40,   93,   52,   40,   40,   87,   52,
       40,   40,   78,   52,   40,   40,   55,   68,   52,   40,
       37,   37,   40,   40,   55,   34,   54,   53,   52,   37,
       37,   34,   31,   31,  129,    3,  129,  129,  129,  129,
      129,  129,  129,  129,  129,  129,  129,  129,  129,  129,
      129,  129,  129,  129,  129,  129,  129,  129,  129,  129,
      129,  129,  129,  129,  129,  129,  129,  129,  129,  129,

      129,  129,  129
    } ;

static yyconst short int yy_chk[404] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    6,
        6,   12,   13,   16,   19,   16,   20,   21,   22,   29,
       29,   19,   23,   20,   26,   22,   22,   24,   36,   23,
       36,   26,   21,   20,   24,   12,   13,   23,   23,   24,
       25,   26,   27,   41,   46,   44,   45,   25,   44,   27,
      140,   25,   48,   48,   41,   27,   44,   46,   45,   49,
       50,   56,  138,   56,   59,   48,   49,   50,   59,   60,

       60,   61,   62,   63,   64,   61,   62,   65,   66,   74,
       65,   63,   69,   71,   69,   72,   66,   72,   64,   75,
       74,   76,   71,   82,   79,   76,   79,   81,   81,   83,
       75,   84,   88,   91,   88,  136,   82,   91,  134,   83,
       84,   94,  132,   94,  130,  128,  130,  130,  131,  131,
      127,  131,  133,  133,  133,  133,  135,  135,  135,  135,
      137,  137,  137,  137,  139,  139,  139,  139,  141,  141,
      141,  141,  142,  142,  142,  142,  143,  143,  143,  143,
      144,  144,  144,  144,  145,  145,  145,  145,  146,  146,
      146,  146,  147,  147,  147,  147,  148,  148,  148,  148,

      149,  149,  149,  149,  150,  150,  150,  150,  151,  151,
      151,  151,  152,  152,  152,  152,  153,  153,  153,  153,
      154,  154,  154,  154,  155,  155,  155,  155,  156,  156,
      156,  156,  157,  157,  157,  157,  158,  158,  158,  158,
      159,  159,  159,  159,  160,  160,  160,  160,  161,  161,
      161,  161,  162,  162,  162,  162,  163,  163,  163,  163,
      164,  164,  164,  164,  165,  165,  165,  165,  166,  166,
      166,  166,  167,  167,  167,  167,  168,  168,  168,  168,
      169,  169,  169,  169,  170,  170,  170,  170,  171,  171,
      171,  171,  172,  172,  172,  172,  173,  173,  173,  173,

      126,  125,  124,  123,  122,  121,  120,  119,  118,  117,
      116,  115,  114,  113,  112,  111,  110,  109,  108,  107,
      106,  105,  104,  103,  102,  101,  100,   99,   98,   96,
       95,   92,   90,   89,   87,   86,   85,   80,   78,   77,
       73,   70,   68,   67,   58,   57,   55,   54,   51,   47,
       43,   42,   39,   38,   35,   34,   33,   32,   30,   18,
       17,   14,   11,    8,    3,  129,  129,  129,  129,  129,
      129,  129,  129,  129,  129,  129,  129,  129,  129,  129,
      129,  129,  129,  129,  129,  129,  129,  129,  129,  129,
      129,  129,  129,  129,  129,  129,  129,  129,  129,  129,

      129,  129,  129
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "NietoTomasProyecto1.l"
#define INITIAL 0
#line 2 "NietoTomasProyecto1.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define MAX_STRING_LENGTH 20
 /* Código por Nieto Rodríguez Tomás Andrés */
 /* Code by Tomás Nieto */
 /* Declaración de contadores y arreglos de tablas pre-existentes, servirán para imprimir los tokens. */
 /*Declaration of pre-existing counters and table arrays, which will be used to print tokens.*/
int symbol_pos = 0;
int literal_real_num_pos = 0;
int literal_int_num_pos = 0;
int literal_str_pos = 0;
int literal_char_pos = 0;
char *RelOp[] = {"^^", "^”", "==", "^^=", "^”=", "<>"};
char *ReservedWords[] = {"cadena", "caracter", "else", "entero", "For", "if", "real", "return", "void", "while"};
char *AsigOp[] = {"~", "+~", "-~", "*~", "/~", "$~"};

 /* Declaración de tipos de datos utilizados en las tablas */
 /* Declaration of data types used in table arrays */
typedef struct {
    int pos;
    char name[100];
    int type;
} Symbol;

typedef struct {
    int pos;
    char data[100];
} Literal;
 /* Declaración del arreglo dinámico para guardar los mensajes de error */
 /* Declaration of the dynamic array used to store error messages */
typedef struct {
    char **messages;
    int size;
    int capacity;
} ErrorList;

 /* Inicialización del arreglo de errores */
 /* Initialization of the error array */
void initErrorList(ErrorList *list, int initial_capacity) 
{
    list->messages = (char **)malloc(initial_capacity * sizeof(char *));
    list->size = 0;
    list->capacity = initial_capacity;
}
 /* Función para añadir elementos al arreglo de errores */
 /* Function used to add elements into the error array */
void addError(ErrorList *list, const char *message) 
{
    if (list->size >= list->capacity) 
	{
        list->capacity *= 2;
        list->messages = (char **)realloc(list->messages, list->capacity * sizeof(char *));
    }
    list->messages[list->size] = (char *)malloc(strlen(message) + 1);
    strcpy(list->messages[list->size], message);
    list->size++;
}

 /* Liberación de la memoria usada para el arreglo de errores */
 /* Function used to free memory used by error array */
void freeErrorList(ErrorList *list) 
{
    for (int i = 0; i < list->size; i++) 
	{
        free(list->messages[i]);
    }
    free(list->messages);
}

 /* Declaración de tablas de literales */
 /* Declaration of literal tables */

Symbol symbol_table[1000];
Literal literal_real_numbers[1000];
Literal literal_integer_numbers[1000];
Literal literal_strings[1000];
Literal literal_characters[1000];

 /* Funciones para añadir elementos a las tablas de literales */
 /* Functions used to add elements into the literal tables */
void add_literal_int_number(char *data)
{
	strcpy(literal_integer_numbers[literal_int_num_pos].data, data);
	literal_integer_numbers[literal_int_num_pos].pos = literal_int_num_pos;
	literal_int_num_pos++;
}

void add_literal_real_number(char *data)
{
	strcpy(literal_real_numbers[literal_real_num_pos].data, data);
	literal_real_numbers[literal_real_num_pos].pos = literal_real_num_pos;
	literal_real_num_pos++;
}

void add_literal_string(char *data)
{
	strcpy(literal_strings[literal_str_pos].data, data);
	literal_strings[literal_str_pos].pos = literal_str_pos;
	literal_str_pos++;
}

void add_literal_char(char *data)
{
	strcpy(literal_characters[literal_char_pos].data, data);
	literal_characters[literal_char_pos].pos = literal_char_pos;
	literal_char_pos++;
}

 /* Algoritmo de busqueda lineal para encontrar elementos en tablas pre-existentes */
 /* Linear search algorithm used to find elements in pre-existing table arrays */ 
int search(char *match, char *arr[], int size)
{
	for(int i = 0; i < size; i++)
	{
		if(strcmp(match, arr[i]) == 0)
		{
			return i;
		}
	}
	return -1;
}

 /* Algoritmo de busqueda lineal para encontrar elementos en la tabla de identificadores */
 /* Linear search algorithm used to find elements in the identifier table */
int find_symbol(char *name) {
    for (int i = 0; i < symbol_pos; i++) {
        if (strcmp(symbol_table[i].name, name) == 0) {
            return symbol_table[i].pos; // Devuelve la posición si se encuentra
        }
    }
    return -1; // Devuelve -1 si no se encuentra
}
 /* Función para añadir simbolos a la tabla de identificadores */
 /* Function used to add symbols into the identifier table */

int add_symbol(char *name, int type)
{
	int pos = find_symbol(name);
    if (pos == -1) 
	{ // Si no se encontró, se agrega el símbolo
	  // If not found, the symbol is added
        strcpy(symbol_table[symbol_pos].name, name);
        symbol_table[symbol_pos].pos = symbol_pos;
        symbol_table[symbol_pos].type = type;
        symbol_pos++;
        pos = symbol_pos - 1;
	}
	return pos;
}

ErrorList errors;
//Expresiones regulares
// Regular expressions
#line 658 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 172 "NietoTomasProyecto1.l"

 /* Clase 0: Palabras reservadas */
 /* Class 0: Reserved words */
#line 813 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 130 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 366 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 175 "NietoTomasProyecto1.l"
{
    int index = search(yytext, ReservedWords, sizeof(ReservedWords)/sizeof(ReservedWords[0]));
    printf("(0, %d)\n", index); /* Palabra reservada */
}
	YY_BREAK
/* Clase 1: Operadores aritméticos */
/* Class 1: Arithmetic operators */
case 2:
YY_RULE_SETUP
#line 182 "NietoTomasProyecto1.l"
{ 
	printf("(1, %s)\n", yytext); 
}
	YY_BREAK
/* Clase 2: Operadores de asignación */
/* Class 2: Assignment operators */
case 3:
YY_RULE_SETUP
#line 188 "NietoTomasProyecto1.l"
{ 
	int value = search(yytext, AsigOp, sizeof(AsigOp)/sizeof(AsigOp[0]));
	printf("(2, %s)\n", yytext); 
}
	YY_BREAK
/* Clase 3: Símbolos especiales */
/* Clase 3: Special symbols */
case 4:
YY_RULE_SETUP
#line 195 "NietoTomasProyecto1.l"
{ 
	printf("(3, %s)\n", yytext); 
}
	YY_BREAK
/* Clase 4: Operadores relacionales */
/* Clase 4: Relational operators */
case 5:
YY_RULE_SETUP
#line 201 "NietoTomasProyecto1.l"
{ 
    int value = search(yytext, RelOp, sizeof(RelOp)/sizeof(RelOp[0])); 
    printf("(4, %d)\n", value);
}
	YY_BREAK
/* Clase 5: Identificadores */
/* Clase 5: Identifiers */
case 6:
YY_RULE_SETUP
#line 208 "NietoTomasProyecto1.l"
{ 
	// Se obtiene la posición al añadir el símbolo o al buscar en la tabla
	// The position is retrieved when adding a symbol and searching in the table
    int pos = add_symbol(yytext, -2);
	printf("(5, %d)\n", pos);
}
	YY_BREAK
/* Clase 6: Constantes numéricas enteras */
/* Clase 6: Integer numeric constants */
case 7:
YY_RULE_SETUP
#line 217 "NietoTomasProyecto1.l"
{ 
	printf("(6, %d)\n", literal_int_num_pos); 
	add_literal_int_number(yytext); 
}
	YY_BREAK
/* Clase 7: Constantes numéricas reales */
/* Class 7: Numeric real constants */
case 8:
YY_RULE_SETUP
#line 224 "NietoTomasProyecto1.l"
{ 
	printf("(7, %d)\n", literal_real_num_pos); 
	add_literal_real_number(yytext); 
}
	YY_BREAK
/* Clase 8: Constantes cadenas */
/* Class 8: String constants */
case 9:
YY_RULE_SETUP
#line 231 "NietoTomasProyecto1.l"
{ 
	printf("(8, %d)\n", literal_str_pos); 
	add_literal_string(yytext); 
}
	YY_BREAK
/* Clase 9: Constantes carácter */
/* Class 9: Character constants */
case 10:
YY_RULE_SETUP
#line 238 "NietoTomasProyecto1.l"
{ 
	printf("(9, %d)\n", literal_char_pos); 
	add_literal_char(yytext); 
}
	YY_BREAK
/* Espacios y saltos de línea */
/* Spacing and line breaks */
case 11:
YY_RULE_SETUP
#line 245 "NietoTomasProyecto1.l"
{ /* Ignorar / Ignore */ }
	YY_BREAK
/* Manejo de errores */
/* Error handling */
case 12:
YY_RULE_SETUP
#line 249 "NietoTomasProyecto1.l"
{
    char error_message[100];
    sprintf(error_message, "Lexical error: %s", yytext);
    addError(&errors, error_message);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 255 "NietoTomasProyecto1.l"
{
	// Ejemplos de ID's ilegales: b2, c4, a8
	// Examples of illegal ID's: b2, c4, a8
    char error_message[100];
    sprintf(error_message, "Lexical error: %s", yytext);
    addError(&errors, error_message);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 264 "NietoTomasProyecto1.l"
ECHO;
	YY_BREAK
#line 1028 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 130 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 130 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 129);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 264 "NietoTomasProyecto1.l"


int yywrap()
{
    return 1;
}

int main(int argc, char **argv)
{
 /* Inicialización del arreglo de errores */
 /* Initialization of error array */
	initErrorList(&errors, 10);
	if (argc < 2)
	{
		printf("Usage: %s <source-file>\n", argv[0]);
		exit(1);
	}
 /* Manejo de archivo */
 /* File handling */
	FILE *source_file = fopen(argv[1], "r");
	
	if (!source_file)
	{
		printf("Error: Cannot open the source file %s\n", argv[1]);
		exit(1);
	}
 
 /* Impresión de tokens */
 /* Token printing */
	printf("Tokens\n");
	
	yyin = source_file;
	yylex();
	
 /* Impresión de tablas */
 /*Table printing */
	printf("\n Symbol Table:\n");
	for(int i = 0; i < symbol_pos; i++)
	{
		printf("Pos: %d, Name: %s\n", symbol_table[i].pos, symbol_table[i].name);
	}
	
	printf("\n Literal Real Table:\n");
	for(int i = 0; i < literal_real_num_pos; i++)
	{
		printf("Pos: %d, Data: %s\n", literal_real_numbers[i].pos, literal_real_numbers[i].data);
	}

	printf("\n Literal Integer Table:\n");
	for(int i = 0; i < literal_int_num_pos; i++)
	{
		printf("Pos: %d, Data: %s\n", literal_integer_numbers[i].pos, literal_integer_numbers[i].data);
	}
	
	
	printf("\n String Literal Table\n");
	for(int i = 0; i < literal_str_pos; i++)
	{
		printf("Pos: %d, Data: %s\n", literal_strings[i].pos, literal_strings[i].data);
	}

	printf("\n Character Literal Table\n");
	for(int i = 0; i < literal_char_pos; i++)
	{
		printf("Pos: %d, Data: %s\n", literal_characters[i].pos, literal_characters[i].data);
	}
 /* Impresión de errores */
 /* Error printing */
	printf("\nErrors\n");
	if (errors.size > 0) {
        printf("Errors found:\n");
        for (int i = 0; i < errors.size; i++) 
		{
            printf("%s\n", errors.messages[i]);
        }
    }
 /* Liberación de memoria del arreglo dinámico de errores */
 /* Dynamic error array memory release */
	freeErrorList(&errors);
	fclose(source_file);
	return 0;
}

			

